config/routes.rb
Rails.application.routes.draw do
  resources :links

  root 'links#index'

  put '/up_vote/:id', to: 'links#up_vote', as: :up_vote
  put '/down_vote/:id', to: 'links#down_vote', as: :down_vote

end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy, :up_vote, :down_vote]

  def index
    @links = Link.all.order(votes: :desc)
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(link_params)
    if @link.save
      redirect_to links_path(@links)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @link.update_attributes(link_params)
      redirect_to @links
    else
      render :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path
  end

  def up_vote
    @link = Link.find(params[:id])
    @link.votes += 1
    @link.save
    redirect_to root_path
  end

  def down_vote
    @link = Link.find(params[:id])
    @link.votes -= 1
    @link.save
    redirect_to root_path
  end

  private
    def link_params
      params.require(:link).permit(:title, :url, :votes)
    end

    def set_link
      @link = Link.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkAggregator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for(@link, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :title %>

  <%= f.input :url %>

  <%= f.input :votes %>

  <%= f.button :submit %>
<% end %>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/index.html.erb
<h1>Links</h1>

<% @links.each do |link| %>
  <div class="well">
    <ul class="list-inline center-block row">
      <li class="col-md-4 valign"><%= link_to link.title, link.url %></li>
      <div class="list-inline col-md-7 valign">
        <li>votes: <%= link.votes %></li>
        <li><%= link_to raw("<i class=\"glyphicon glyphicon-arrow-up\">Vote</i>"), up_vote_path(link.id),  class: "btn btn-default", method: :put %>
        <li><%= link_to raw("<i class=\"glyphicon glyphicon-arrow-down\">Vote</i>"), down_vote_path(link.id),  class: "btn btn-default", method: :put %>
      </div>
      <li class="pull-right col-md-1 valign"><%= link_to "Link", link_path(link.id), class: 'btn btn-primary' %></li>
    </ul>
  </div>
<% end %>
<%= link_to 'New Link', new_link_path, class: 'btn btn-primary' %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'back', links_path %>

app/views/links/show.html.erb
<h1>Link</h1>

  <div class="well">
    <ul class="list-inline">
      <li><%= @link.title %></li>
      <li><%= @link.url %></li>
      <li><%= @link.votes %></li>
      <li class="pull-right"><%= link_to 'Back', links_path %></li>
      <li class="pull-right"><%= link_to 'Delete', link_path(@link.id), method: :delete %></li>
    </ul>
  </div>